[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
colorous = "1.0.15"
image = "0.25.5"
num-complex = "0.4.6"
rayon = "1.10.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
